export const QUERIES_KEYS = {
  STAFF: {
    STAFF_LIST: "STAFF_LIST",
    STAFF_DETAILS: "STAFF_DETAILS",
    STAFF_PROJECTS: "STAFF_PROJECTS",
  },
  PROJECTS: {
    PROJECT_LIST: "PROJECT_LIST",
    PROJECT_DETAILS: "PROJECT_DETAILS",
  },
  PARTICIPATION: {
    STAFF_WITH_PROJECTS: "STAFF_WITH_PROJECTS",
  },
};
